### ISSUE TITLE
mqtt-client-React example does not work

### ISSUE THREAD

**Issue by ymwjbxxq** [emqx/MQTT-Client-Examples#66]
Hello,

I tried to run the mqtt-client-React, and this is the error:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/mypath/git/mqtt-client-React/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/mypath/git/mqtt-client-React/node_modules/webpack/lib/NormalModule.js:417:16)
    at /mypath/git/mqtt-client-React/node_modules/webpack/lib/NormalModule.js:452:10
    at /mypath/git/mqtt-client-React/node_modules/webpack/lib/NormalModule.js:323:13
    at /mypath/git/mqtt-client-React/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /mypath/git/mqtt-client-React/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/mypath/git/mqtt-client-React/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /mypath/git/mqtt-client-React/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0
error Command failed with exit code 1.
```

**Comment by 0721Betty** [comment]
Try to change the Node.js version from v18.13.0 to v16.16.0

**Comment by 0721Betty** [comment]
updated
